# -*- coding: utf-8; mode: python; -*-

from bb.app.os.drivers.leds import LEDMatrixDriver

cc_library_factory(target = LEDMatrixDriver,
                   srcs = [gen_msngr_runner_c(["bb/os/drivers/leds/led_matrix_driver.c"])])
