# -*- coding: utf-8; mode: python; -*-

from bb.app.os.drivers.gpio import ButtonDriver

cc_library_factory(target = ButtonDriver,
                   srcs = [gen_msngr_runner_c(["bb/os/drivers/gpio/button.c"])])
