/*
 * Author: Oleksandr Sviridenko
 */
#ifndef __BB_OS_DRIVERS_PROCESSORS_PROPELLER_P8X32A_INIT_H
#define __BB_OS_DRIVERS_PROCESSORS_PROPELLER_P8X32A_INIT_H

#endif /* __BB_OS_DRIVERS_PROCESSORS_PROPELLER_P8X32A_INIT_H */
