/*
 * Wrapper for <stdlib.h> header file
 *
 * Copyright (c) 2011-2013 Sladeware LLC
 */
#ifndef __STDLIB_H
#define __STDLIB_H

/* The macros are NULL, EXIT_FAILURE, EXIT_SUCCESS, RAND_MAX, and MB_CUR_MAX.*/
#define NULL ((void *)0)

#define EXIT_FAILURE       1 /* standard error return using exit() */
#define EXIT_SUCCESS       0 /* successful return using exit() */
#define RAND_MAX       32767 /* largest value generated by rand() */
#define MB_CUR_MAX         1 /* max value of multibyte character in MINIX */

typedef struct { int quot, rem; } div_t;
typedef struct { long quot, rem; } ldiv_t;

/* Function prototypes */
PROTOTYPE(void abort, (void));
PROTOTYPE(int abs, (int _j));
PROTOTYPE(int atexit, (void (*_func)(void)));
PROTOTYPE(double atof, (const char *_nptr));
PROTOTYPE(int atoi, (const char *_nptr));
PROTOTYPE(long atol, (const char *_nptr));
PROTOTYPE(void *calloc, (size_t _nmemb, size_t _size));
PROTOTYPE(div_t div, (int _numer, int _denom));
PROTOTYPE(void exit, (int _status));
PROTOTYPE(void free, (void *_ptr));
PROTOTYPE(char *getenv, (const char *_name));
PROTOTYPE(long labs, (long _j));
PROTOTYPE(ldiv_t ldiv, (long _numer, long _denom));
PROTOTYPE(void *malloc, (size_t _size));
PROTOTYPE(int mblen, (const char *_s, size_t _n));
PROTOTYPE(size_t mbstowcs, (wchar_t *_pwcs, const char *_s, size_t _n));
PROTOTYPE(int mbtowc, (wchar_t *_pwc, const char *_s, size_t _n));
PROTOTYPE(int rand, (void));
PROTOTYPE(void *realloc, (void *_ptr, size_t _size));
PROTOTYPE(void srand, (unsigned int _seed));
PROTOTYPE(double strtod, (const char *_nptr, char** _endptr));
PROTOTYPE(long strtol, (const char *_nptr, char **_endptr, int _base));
PROTOTYPE(int system, (const char *_string));
PROTOTYPE(size_t wcstombs, (char *_s, const wchar_t *_pwcs, size_t _n));
PROTOTYPE(int wctomb, (char *_s, wchar_t _wchar));
PROTOTYPE(void *bsearch, (const void* _key, const void* _base, size_t _nmemb,
                          size_t _size, int (*compar)(const void*, const void*)));
PROTOTYPE( void qsort, (void *_base, size_t _nmemb, size_t _size,
                        int (*compar) (const void*, const void*)));
PROTOTYPE( unsigned long int strtoul,
           (const char* _nptr, char** _endptr, int _base));

#endif /* __STDLIB_H */
